// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Illuminate.Migrations
{
    [DbContext(typeof(IlluminateContext))]
    [Migration("20210919141717_test2")]
    partial class test2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("DataLayer.EDiscordMember", b =>
                {
                    b.Property<int>("DbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("DbId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("DataLayer.EReactionMessage", b =>
                {
                    b.Property<int>("DbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("DbId");

                    b.ToTable("ReactionMessages");
                });

            modelBuilder.Entity("DataLayer.EString", b =>
                {
                    b.Property<int>("DbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("String")
                        .HasColumnType("TEXT");

                    b.HasKey("DbId");

                    b.ToTable("SwearWords");
                });

            modelBuilder.Entity("DataLayer.EmojiRolePair", b =>
                {
                    b.Property<int>("DbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EReactionMessageDbId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("EmojiId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DbId");

                    b.HasIndex("EReactionMessageDbId");

                    b.ToTable("EmojiRolePair");
                });

            modelBuilder.Entity("DataLayer.EmojiRolePair", b =>
                {
                    b.HasOne("DataLayer.EReactionMessage", null)
                        .WithMany("Pairs")
                        .HasForeignKey("EReactionMessageDbId");
                });

            modelBuilder.Entity("DataLayer.EReactionMessage", b =>
                {
                    b.Navigation("Pairs");
                });
#pragma warning restore 612, 618
        }
    }
}
